name: Deploy ERPv2 API to Azure App Service

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore src/ERP.API/ERP.API.csproj

      - name: Publish
        run: dotnet publish src/ERP.API/ERP.API.csproj -c Release -r win-x86 --self-contained true -o ./publish /p:UseAppHost=true /p:AspNetCoreHostingModel=OutOfProcess

      - name: Verify SqlClient runtime assets
        shell: pwsh
        run: |
          Get-ChildItem -Path .\publish -Filter *SqlClient* | Select-Object Name,Length | Format-Table -AutoSize

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_56F0DEAEF5CA45E5802DF14EDE31940B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E5A2D5AA278149DFABB2DA6E02C076AC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_34EC648C249C407A9A221CA1885FAA83 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: stoknet
          package: ./publish
